steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Build and Deploy to Dev Server
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    gcloud compute ssh gdg@gdg-fest-mdn-env-dev --zone=asia-southeast2-a --command='/bin/sh cd /home/gdg/gdg-fest-mdn-be; ./deploy.sh'
options:
  logging: CLOUD_LOGGING_ONLY
